---
- name: "Checking bind records are defined"
  ansible.builtin.assert:
    that:
      - iac_fs_binds is defined
    fail_msg: "iac_fs_binds must be defined"

- name: "Including shared bind mount absent tasks"
  ansible.builtin.include_tasks: shared/bind_absent.yml
