---
###############################################################################
#
# databases_absent.yml
#
###############################################################################

- name: "Setting database variables"
  ansible.builtin.set_fact:
    pg_databases: "{{ pg_instance_record.1.databases | default([]) }}"
    pg_instance: "{{ pg_instance_record.1.name }}"
    pg_replication_role: "{{ pg_instance_record.1.replication.role | default('off') }}"
    pg_version: "{{ pg_instance_record.0.version | string }}"
    pg_port: "{{ pg_instance_record.1.configuration.port | default(pg_default_port) }}"
  when: pg_instance_record is defined

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - pg_databases is defined
      - pg_instance is defined
      - pg_version is defined
      - pg_port is defined
    fail_msg: "PostgreSQL databases_absent state is missing one or more required variables"

- name: "Checking databases are not managed on standby replication instances"
  ansible.builtin.assert:
    that:
      - pg_replication_role != 'standby'
    fail_msg: "PostgreSQL databases_absent must not be run for standby replication instances"

- name: "Looping through databases"
  ansible.builtin.include_tasks: "database_absent.yml"
  loop: "{{ pg_databases }}"
  loop_control:
    loop_var: pg_database_record
