---
###############################################################################
#
# extension_package_present.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Setting what variables are configured"
  ansible.builtin.set_fact:
    pg_extension: "{{ pg_extension_record.name | default(omit) }}"
    pg_timescaledb_source: "{{ pg_extension_record.source | default('pgdg') }}"
    pg_instance: "{{ pg_instance_record.1.name }}"
    pg_version: "{{ pg_instance_record.0.version | string }}"
    pg_port: "{{ pg_instance_record.1.configuration.port | default(pg_default_port) }}"

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - pg_version is defined
    fail_msg: "PostgreSQL extension package state is missing one or more required variables"

- name: "Ensuring TimescaleDB Community repository is present"
  ansible.builtin.include_tasks: timescaledb_repo_present.yml
  when:
    - pg_extension == 'timescaledb'
    - pg_timescaledb_source == 'community'

###############################################################################
# ENSURING EXTENSIONS ARE PRESENT
###############################################################################

- name: "Ensuring required PostgreSQL extension packages are installed"
  ansible.builtin.include_tasks: package_present.yml
  loop:
    - name: citus
      package: "citus_{{ pg_version }}"
    - name: pg_cron
      package: "pg_cron_{{ pg_version }}"
    - name: pgaudit
      package: "pgaudit_{{ pg_version }}"
    - name: postgis35
      package: "postgis35_{{ pg_version }}"
    - name: postgis36
      package: "postgis36_{{ pg_version }}"
    - name: set_user
      package: "set_user_{{ pg_version }}"
    - name: timescaledb
      package: >-
        {{
          'timescaledb-2-postgresql-' ~ pg_version
          if pg_timescaledb_source == 'community'
          else 'timescaledb_' ~ pg_version
        }}
    - name: plpython3u
      package: "postgresql{{ pg_version }}-plpython3"
  loop_control:
    loop_var: ext
  vars:
    pg_package: "{{ ext.package }}"
  when:
    - pg_extension is defined
    - pg_extension == ext.name
    - pg_version in ["16", "17", "18"]
    - (ansible_facts["distribution"] in ['RedHat', 'Rocky'] and ansible_facts["distribution_major_version"] in ['10', '9', '8']) or
      (ansible_facts["distribution"] in ['Fedora'] and ansible_facts["distribution_major_version"] in ['41','42'])
