---
###############################################################################
#
# log_write.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# WRITING LOGS
###############################################################################

- name: "Adding log to task-report"
  ansible.builtin.shell: >
    echo "{{ ansible_date_time.iso8601 }} {{ ansible_ssh_user | default(lookup('env', 'USER')) }} {{ iac_service_name }} {{ iac_log_write }}" >> {{ iac_ansible_report_tasks_path }}
  register: my_output
  changed_when: false
  failed_when: my_output.rc != 0
  when: iac_ansible_report and iac_ansible_report_tasks_path is defined and iac_log_write is defined

- name: "Clearing log variables"
  ansible.builtin.set_fact:
    iac_log_write: null
  when: iac_ansible_report
