---
###############################################################################
#
# loop_instances.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - pg_bind_dir is defined
      - pg_encoding is defined
      - pg_instances is defined
      - pg_lc_collate is defined
      - pg_lc_ctype is defined
    fail_msg: "PostgreSQL instance loop is missing one or more required variables"

###############################################################################
# LOOPING THROUGH INSTANCES
###############################################################################

- name: "Looping through instances"
  ansible.builtin.include_tasks: "{{ pg_state }}.yml"
  loop: "{{ pg_instances }}"
  loop_control:
    loop_var: pg_instance_record
  when: >-
    pg_instance_provider is not defined
    or (
      pg_instance_provider == 'standalone'
      and (
        (
          pg_instance_record.0.clusters | default([])
          | selectattr('name', 'equalto', pg_instance_record.1.cluster | default(''))
          | map(attribute='provider') | first | default('standalone')
        ) != 'patroni'
      )
    )
    or (
      pg_instance_provider != 'standalone'
      and
      (
        pg_instance_record.0.clusters | default([])
        | selectattr('name', 'equalto', pg_instance_record.1.cluster | default(''))
        | map(attribute='provider') | first | default('standalone')
      ) == pg_instance_provider
    )
