---
###############################################################################
#
# package_absent.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - dnf_disable_gpg_check is defined
      - dnf_sslverify is defined
      - dnf_validate_certs is defined
      - http_proxy is defined
      - https_proxy is defined
      - no_proxy is defined
      - pg_package is defined
    fail_msg: "PostgreSQL package removal is missing one or more required variables"

- name: "Normalizing package list for removal"
  ansible.builtin.set_fact:
    pg_package_list: >-
      {{
        pg_package
        if (pg_package is sequence and pg_package is not string)
        else
        (
          pg_package.split(',')
          | map('trim')
          | reject('equalto', '')
          | list
        )
      }}

###############################################################################
# ENSURING PACKAGE IS ABSENT
###############################################################################

- name: "Ensuring packages are absent"
  ansible.builtin.command:
    argv: >-
      {{
        [
          'dnf',
          '-y',
          'remove',
          '--setopt=sslverify=' ~ (1 if dnf_sslverify else 0),
          '--nogpgcheck' if dnf_disable_gpg_check else '--setopt=gpgcheck=1'
        ] + pg_package_list
      }}
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  changed_when: false
  when:
    - pg_package is defined
    - ansible_facts["os_family"] == "RedHat"
    - ansible_facts["distribution_major_version"] == "8"

- name: "Ensuring packages are absent"
  ansible.builtin.dnf:
    name: "{{ pg_package_list }}"
    sslverify: "{{ dnf_sslverify }}"
    validate_certs: "{{ dnf_validate_certs }}"
    disable_gpg_check: "{{ dnf_disable_gpg_check }}"
    state: "absent"
  vars:
    ansible_python_interpreter: "{{ pg_package_module_interpreter }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  when:
    - pg_package is defined
    - not
      (
        ansible_facts["os_family"] == "RedHat"
        and ansible_facts["distribution_major_version"] == "8"
      )
- name: "Writing log"
  ansible.builtin.include_tasks: log_write.yml
  vars:
    iac_log_write: "Ensured {{ pg_package }} was removed"
  when: pg_package is defined
