---
###############################################################################
#
# post_present.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - iac_post_install_job is defined
    fail_msg: "PostgreSQL post-install state is missing one or more required variables"

###############################################################################
# LOOPING THROUGH DIRECTORIES
###############################################################################

- name: "Running PostgreSQL post-install SQL"
  become: true
  become_user: "postgres"
  ansible.builtin.command:
    argv:
      - "/usr/pgsql-{{ pg_version }}/bin/psql"
      - "{{ iac_post_install_job.database | default('postgres') }}"
      - "-p"
      - "{{ pg_port | string }}"
      - "-v"
      - "ON_ERROR_STOP=1"
  args:
    stdin: "{{ iac_post_install_job.sql }}"
  changed_when: true
