---
###############################################################################
#
# repo_present_el9.yml
#
# @author Arsi Atomi
#
###############################################################################

- name: "Ensuring Rocky 9 CRB repository is enabled"
  ansible.builtin.command: "dnf config-manager --set-enabled crb"
  register: pg_crb_enable
  changed_when: false
  failed_when: false
  when:
    - ansible_facts["distribution"] == "Rocky"
    - pg_repofile_available is true

- name: "Falling back to repo file enablement for Rocky 9 CRB repository"
  ansible.builtin.include_tasks: repo_enable_in_file.yml
  vars:
    pg_repo_enable_file: "/etc/yum.repos.d/rocky.repo"
    pg_repo_enable_section: "crb"
  when:
    - ansible_facts["distribution"] == "Rocky"
    - pg_repofile_available is true
    - pg_crb_enable.rc != 0

- name: "Checking Rocky 9 CRB repository is enabled"
  ansible.builtin.command: "dnf repolist --enabled crb"
  register: pg_crb_repo_check
  changed_when: false
  failed_when: pg_crb_repo_check.rc != 0
  when:
    - ansible_facts["distribution"] == "Rocky"
    - pg_repofile_available is true

- name: "Ensuring PostgreSQL AppStream module is disabled on EL9"
  ansible.builtin.command: "dnf -qy module disable postgresql"
  register: pg_module_disable
  changed_when: false
  failed_when:
    - pg_module_disable.rc != 0
    - >-
      'missing groups or modules: postgresql'
      not in (pg_module_disable.stderr | default(''))
  when: pg_disable_postgresql_module | bool
