---
###############################################################################
#
# repo_present.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - dnf_disable_gpg_check is defined
      - dnf_validate_certs is defined
      - dnf_sslverify is defined
      - dnf_update_cache is defined
      - http_proxy is defined
      - https_proxy is defined
      - no_proxy is defined
      - pg_dnf_repo_path is defined
      - pg_version is defined
    fail_msg: "All tests did not pass"

###############################################################################
# DISPATCHING DISTRIBUTION-SPECIFIC REPOSITORY SETUP
###############################################################################

- name: "Ensuring PostgreSQL repository is present for RedHat family"
  ansible.builtin.include_tasks: repo_present_redhat_family.yml
  when: ansible_facts["distribution"] in ["RedHat", "Rocky"]

- name: "Ensuring PostgreSQL repository is present for Fedora"
  ansible.builtin.include_tasks: repo_present_fedora.yml
  when: ansible_facts["distribution"] == "Fedora"
