---
###############################################################################
#
# repo_absent.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - pg_dnf_repo_path is defined
      - dnf_disable_gpg_check is defined
      - dnf_sslverify is defined
      - dnf_validate_certs is defined
      - dnf_update_cache is defined
      - http_proxy is defined
      - https_proxy is defined
      - no_proxy is defined
    fail_msg: "All tests did not pass"

###############################################################################
# REMOVING REPOSITORY
###############################################################################

- name: "Setting PostgreSQL repository package names for removal"
  ansible.builtin.set_fact:
    pg_repo_packages:
      - "pgdg-redhat-repo"
      - "pgdg-fedora-repo"

- name: "Gathering installed package facts"
  ansible.builtin.package_facts:
    manager: auto

- name: "Ensuring PostgreSQL repository packages are absent"
  ansible.builtin.dnf:
    name: "{{ pg_repo_packages | select('in', ansible_facts.packages.keys() | list) | list }}"
    sslverify: "{{ dnf_sslverify }}"
    validate_certs: "{{ dnf_validate_certs }}"
    disable_gpg_check: "{{ dnf_disable_gpg_check }}"
    update_cache: "{{ dnf_update_cache }}"
    state: absent
  vars:
    ansible_python_interpreter: "{{ pg_package_module_interpreter }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  when: >
    (pg_repo_packages | select('in', ansible_facts.packages.keys() | list) | list | length) > 0

- name: "Removing repository file"
  ansible.builtin.file:
    path: "{{ pg_dnf_repo_path }}"
    state: absent

- name: "Removing TimescaleDB Community repository file"
  ansible.builtin.file:
    path: "{{ pg_timescaledb_repo_file }}"
    state: absent
  when: pg_timescaledb_repo_file is defined

- name: "Writing log"
  ansible.builtin.include_tasks: log_write.yml
  vars:
    iac_log_write: "Removed PostgreSQL repository files"
