---
###############################################################################
#
# version_absent.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Setting version variables"
  ansible.builtin.set_fact:
    pg_version: "{{ pg_version_record.version | string }}"
    iac_cron: "{{ pg_version_record.cron | default([]) }}"
    iac_fs_directories: "{{ pg_version_record.directories | default([]) }}"
    iac_fs_files: "{{ pg_version_record.files | default([]) }}"
    iac_fs_binds: >-
      {{
        pg_version_record.binds
        | default([])
        | map('combine', {'purge_on_absent': true})
        | list
      }}
    iac_git_repos: "{{ pg_version_record.git | default([]) }}"
  when: pg_version_record is defined

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - dnf_disable_gpg_check is defined
      - dnf_sslverify is defined
      - dnf_validate_certs is defined
      - http_proxy is defined
      - https_proxy is defined
      - no_proxy is defined
      - pg_version is defined
    fail_msg: "All tests did not pass"

- name: "Checking PostgreSQL version-scoped bind records type"
  ansible.builtin.assert:
    that:
      - pg_version_record.binds is not defined or (pg_version_record.binds | type_debug) == 'list'
    fail_msg: "pg_versions[].binds must be a list"

###############################################################################
# ENSURING PACKAGES ARE REMOVED
###############################################################################

- name: "Ensuring PostgreSQL packages are removed"
  ansible.builtin.include_tasks: package_absent.yml
  vars:
    pg_package: "postgresql{{ pg_version }}-server,postgresql{{ pg_version }}-contrib,postgresql{{ pg_version }}-libs,postgresql{{ pg_version }}"

- name: "Ensuring cron configuration is absent"
  ansible.builtin.include_tasks: cron_absent.yml
  when: (iac_cron | default([])) | length > 0

- name: "Ensuring bind mount configuration is absent"
  ansible.builtin.include_tasks: bind_absent.yml
  when: (iac_fs_binds | default([])) | length > 0

- name: "Ensuring git repositories are absent"
  ansible.builtin.include_tasks: git_absent.yml
  when: (iac_git_repos | default([])) | length > 0

- name: "Ensuring filesystem configuration is absent"
  ansible.builtin.include_tasks: fs_absent.yml
  when: (iac_fs_directories | default([])) | length > 0 or (iac_fs_files | default([])) | length > 0
