---
###############################################################################
#
# version_state.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Setting version variables"
  ansible.builtin.set_fact:
    pg_version: "{{ pg_version_record.version | string }}"
    iac_cron: "{{ pg_version_record.cron | default([]) }}"
    iac_fs_directories: "{{ pg_version_record.directories | default([]) }}"
    iac_fs_files: "{{ pg_version_record.files | default([]) }}"
    iac_git_repos: "{{ pg_version_record.git | default([]) }}"
  when: pg_version_record is defined

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - dnf_disable_gpg_check is defined
      - dnf_sslverify is defined
      - dnf_validate_certs is defined
      - http_proxy is defined
      - https_proxy is defined
      - no_proxy is defined
      - pg_version is defined
    fail_msg: "All tests did not pass"

###############################################################################
# ENSURING REPOSITORIES ARE PRESENT
###############################################################################

- name: "Ensuring PostgreSQL repositories are present"
  ansible.builtin.include_tasks: repo_present.yml

###############################################################################
# ENSURING PACKAGES ARE INSTALLED
###############################################################################

- name: "Ensuring PostgreSQL packages are installed"
  ansible.builtin.include_tasks: package_present.yml
  vars:
    pg_package: "postgresql{{ pg_version }}-server,postgresql{{ pg_version }}-contrib"

###############################################################################
# ENSURING FILESYSTEM CONFIGURATION
###############################################################################

- name: "Ensuring filesystem configuration is present"
  ansible.builtin.include_tasks: fs_present.yml
  when: (iac_fs_directories | default([])) | length > 0 or (iac_fs_files | default([])) | length > 0

- name: "Ensuring git is installed if repositories are configured"
  ansible.builtin.include_tasks: package_present.yml
  vars:
    pg_package: "git"
  when: (iac_git_repos | default([])) | length > 0

- name: "Ensuring git repositories are present"
  ansible.builtin.include_tasks: git_present.yml
  vars:
    iac_git_become_user: "{{ pg_os_user }}"
  when: (iac_git_repos | default([])) | length > 0

###############################################################################
# ENSURING CRONJOB CONFIGURATION
###############################################################################

- name: "Ensuring cron configuration is present"
  ansible.builtin.include_tasks: cron_present.yml
  when: (iac_cron | default([])) | length > 0
