# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if 'rockylinux:8-' in item.image %}
RUN dnf makecache && \
    dnf --assumeyes install python39 openssl sudo bash iproute && \
    dnf clean all
{% else %}
RUN dnf makecache && \
    dnf --assumeyes install python3 openssl sudo bash iproute && \
    dnf clean all
{% endif %}
