# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN dnf makecache && \
    dnf --assumeyes install python39 sudo bash iproute && \
    dnf clean all
