# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN dnf --assumeyes install python3 python3-libdnf5 sudo bash iproute openssl systemd && \
    dnf clean all
