---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: instance-idarsi-validation
    image: docker.io/rockylinux/rockylinux:9-ubi-init
    command: /sbin/init
    privileged: true
    pre_build_image: true
    systemd: "true"
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: instance-idarsi-etcd
    image: docker.io/rockylinux/rockylinux:9-ubi-init
    command: /sbin/init
    privileged: true
    pre_build_image: true
    systemd: "true"
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
    ANSIBLE_CALLBACK_PLUGINS: "${MOLECULE_SCENARIO_DIRECTORY}/callback_plugins"
    ANSIBLE_CALLBACKS_ENABLED: "validation_capture"
    IDARSI_VALIDATION_CALLBACK_ROOT: "${MOLECULE_EPHEMERAL_DIRECTORY}"
    IDARSI_VALIDATION_CALLBACK_PATH: "${MOLECULE_EPHEMERAL_DIRECTORY}/validation-callback.log"

scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: ansible
  env:
    IDARSI_VALIDATION_CALLBACK_ROOT: "${MOLECULE_EPHEMERAL_DIRECTORY}"
    IDARSI_VALIDATION_CALLBACK_PATH: "${MOLECULE_EPHEMERAL_DIRECTORY}/validation-callback.log"
