---
- name: "Install TimescaleDB"
  hosts: all
  become: false
  vars:
    state: install
    pg_lang: "en"
    pg_locale: "US"
    pg_disable_postgresql_module: false
    ansible_become_method: su
    iac_blueprint:
      postgresql:
        - version: 17
          instances:
            - name: main
              databases:
                - name: metrics
                  extensions:
                    - name: timescaledb
                      source: "{{ timescaledb_source }}"
              configuration:
                port: 5417
  roles:
    - ansible-iac-role-postgresql
