---
- name: "Install TimescaleDB from PGDG"
  hosts: instance-idarsi-timescaledb-pgdg
  become: false
  vars:
    state: install
    pg_lang: "en"
    pg_locale: "US"
    pg_disable_postgresql_module: false
    ansible_become_method: su
    iac_blueprint:
      postgresql:
        - version: 17
          instances:
            - name: main
              databases:
                - name: metrics
                  extensions:
                    - name: timescaledb
              configuration:
                port: 5417
  roles:
    - ansible-iac-role-postgresql

- name: "Install TimescaleDB from the Community repository"
  hosts: instance-idarsi-timescaledb-community
  become: false
  vars:
    state: install
    pg_lang: "en"
    pg_locale: "US"
    pg_disable_postgresql_module: false
    ansible_become_method: su
    iac_blueprint:
      postgresql:
        - version: 17
          instances:
            - name: main
              databases:
                - name: metrics
                  extensions:
                    - name: timescaledb
                      source: community
              configuration:
                port: 5417
  roles:
    - ansible-iac-role-postgresql
